### ISSUE TITLE
What licence is fireworks js?

### ISSUE THREAD

**Issue by yochannah** [reactome-pwp/fireworks-js#1]
Hiya! 

I'm thinking of integrating the pathways overview tool into a page I'm working on, and I was wondering what licence the code is realeased under? Is it ok to take fireworks.js and bundle it in to an app as a library?

**Comment by fabregat** [comment]
Hi there!

It is free to use (under CC BY 4.0, please find more info at https://reactome.org/license).

You can find more information on how to use the fireworks widget at https://reactome.org/dev/pathways-overview/js

Thank you for your interest in using Reactome!

Cheers

**Comment by yochannah** [comment]
Thanks @fabregat - that helps! I've submitted a PR to add the licence to the repo to make it easier to find in the future.: https://github.com/reactome-pwp/fireworks-js/pull/2
