### ISSUE TITLE
Code examples for FireworksJS API methods?

### ISSUE THREAD

**Issue by yochannah** [reactome-pwp/fireworks-js#3]
Hi! Sorry, I have another question about fireworks. Is it possible to add more examples of how the various API methods are run? I've managed to guess a couple based on [the spec](https://reactome.org/dev/pathways-overview/js#API) - so I don't have to configure a proxy server-side, which is brilliant! But I wasn't sure how to call methods like `flagItems`, `highlightNodes`, `selectNode`, etc.

My best guesses looked something like this:

```javascript 
      ////Trying to focus pathways viewer on a gene name GATA1
              fireworks.flagItems("GATA1");
      //// This is a pathway for the D. melanogaster gene "bsk"
      //// Trying to guess correct syntax - all result in console errors
              fireworks.flagItems("04141");
              fireworks.flagItems({identifier : "04141"});
             fireworks.flagItems({identifier : 04141});
              fireworks.flagItems({Identifier : 04141});
              fireworks.flagItems({"Identifier" : "04141"});
      //// Try a different method
              fireworks.highlightNode({stId: "04141"});
              fireworks.highlightNode({identifier: "04141"});
      //// Try identifier gleaned from onNodeSelected...?
              fireworks.highlightNode("R-HSA-390918");
```
All resulted in console errors that looked like this 
![image](https://user-images.githubusercontent.com/9271438/44341632-60b45400-a480-11e8-842f-96bb352cec3a.png)

You can also see a demo - [live demo](https://yochannah.github.io/reactome-fireworks-test/index.html) and [source](https://github.com/yochannah/reactome-fireworks-test/blob/master/index.html#L31-L45)

Any idea what I'm doing wrong? I'd also be happy to help update the docs with examples once I've figured out my mistake, if you tell me where to edit them :)

**Comment by fabregat** [comment]
To select or highlight elements, you need to call
- selectNode(stId) :: void
- highlightNode(stId) :: void

methods respectively. Please note that for both methods the documentation (https://reactome.org/dev/pathways-overview/js#API) says:

  item stable identifier
  stId : string

So it means that you need to pass the Reactome stable identifier for the pathway you wish to either select or highlight. Examples:

- To select the pathway "Sulfur amino acid metabolism" you have to use the "selectNode" method with its stable identifier "R-HSA-1614635".

```
fireworks.selectNode("R-HSA-1614635");
```

- To highlight it, please use the highlightNode method with its stable identifier instead:

```
fireworks.highlightNode("R-HSA-1614635");
```

Finally, the documentation for flagItems says that it "Flags pathways where the identifier is found. It accepts main identifiers but also cross references, gene names and physical entity stable identifiers":

 - flagItems(String identifier) :: void

  Item identifier 
  identifier : string

So you for example can use "PTEN" as the gene name to highlight all pathways where this gene plays a role in. Example:

```
firewors.flagItems("PTEN")
```

**Comment by fabregat** [comment]
BTW, for GATA1 you should get 8 pathways flagged. See it at 

https://reactome.org/PathwayBrowser/#/FLG=GATA1

**Comment by yochannah** [comment]
@fabregat Thanks for your response! I've tried copying and pasting your demo code above directly and I'm still getting the same error: http://jsbin.com/gifacal/edit?html,js,output - any idea at all what I'm doing wrong?

**Comment by fabregat** [comment]
Hi again,

See this http://jsbin.com/xexusojene/1/edit?html,js,output

If you were to replace your html by the following one, then it works for me:

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    Bluegenes Reactome Pathway Viewer
  </title>

  <script type="text/javascript" language="javascript" src="https://reactome.org/FireworksJs/fireworks/fireworks.nocache.js"></script>

  <script type="text/javascript" language="javascript">
    //Creating the Reactome pathways overview widget
    function onReactomeFireworksReady() {
      //This function is automatically called when the widget code is ready to be used
      fireworks = Reactome.Fireworks.create({
        "placeHolder": "fireworksHolder",
        "width": 930,
        "height": 500
      });

      fireworks.onNodeSelected(function(selected) {
        console.info("Selected ", selected);
      });

      fireworks.onFireworksLoaded(onFireworksLoaded);

    }

    function onFireworksLoaded() {
      fireworks.flagItems("GATA1");
      fireworks.selectNode("R-HSA-390918");
    }
</script>
</head>

<body>
  <div class="bluegenesToolReactome" id='yourDiv'>
    <div id="fireworksHolder"></div>
  </div>
</body>

</html>
```
Cheers,

**Comment by yochannah** [comment]
A-ha!

I thought it might be something like that - calling the methods before the script was ready - but it was a little hard to tell with the error from the minified script. Throwing clearer errors might be a nice little improvement, and/or adding a more extensive example to the api documentation.

Awesome, thanks!! :)
